name: Add bugs to bugs project

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created, edited]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/users/jnidzwetzki/projects/2
          github-token: ${{ secrets.ORG_AUTOMATION_TOKEN }}
          labeled: bug, needs-triage
          label-operator: OR

  debug:
    name: Debug output
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2

  waiting-for-author:
    name: Waiting for Author
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'need-more-info'
    steps:
      - uses: leonsteinhaeuser/project-beta-automations@v2.0.0
        with:
          gh_token: ${{ secrets.ORG_AUTOMATION_TOKEN }}
          user: jnidzwetzki
          # organization: sample-org
          project_id: 2
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: 'Waiting for Author'

  waiting-for-engineering:
    name: Waiting for Engineering
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && !github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'need-more-info')
    steps:
      - name: Check if organization member
        id: is_organization_member
        uses: jamessingleton/is-organization-member@1.0.1
        with:
          organization: timescale
          username: ${{ github.GITHUB_ACTOR }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Remove need-more-info label
        if: steps.is_organization_member.outputs.result == false
        uses: andymckay/labeler@3a4296e9dcdf9576b0456050db78cfd34853f260
        with:
          remove-labels: 'need-more-info'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Move to waiting for engineering column
        if: steps.is_organization_member.outputs.result == false
        uses: leonsteinhaeuser/project-beta-automations@v2.0.0
        with:
          gh_token: ${{ secrets.ORG_AUTOMATION_TOKEN }}
          user: jnidzwetzki
          # organization: sample-org
          project_id: 2
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: 'Waiting for Engineering'
