name: Add bugs to bugs project

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created, edited]
    
jobs:
  waiting-for-engineer:
    name: Waiting for Engineer
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && !github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'need-more-info')
    steps:
      - name: remove need-more-info label
        uses: andymckay/labeler@5c59dabdfd4dd5bd9c6e6d255b01b9d764af4414
        with:
          remove-labels: 'need-more-info'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
